services:
  - type: web
    name: flashsale-backend
    runtime: python
    buildCommand: |
              pip install -r requirements.txt
              python manage.py migrate
    startCommand: gunicorn flashsale_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://guna_user:1CK6mjFyQJQKfyRfozxoG4GyqYUovnts@dpg-d0gvddje5dus73anm4g0-a.oregon-postgres.render.com/guna
